version: '3.1'

services:
  # This is the database (postgres)
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7.7-standalone
    ports:
      - 8080:8080